In [2]:
import pandas as pd
import numpy as np
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, func
database_path = "Resources/FPA_FOD_20170508.sqlite"

In [2]:
# Create Engine
engine = create_engine(f"sqlite:///{database_path}")
conn = engine.connect()

In [3]:
# Query All Records in the the Database
data = pd.read_sql("SELECT * FROM Fires", conn)

In [4]:
data.head()

,OBJECTID,FOD_ID,FPA_ID,SOURCE_SYSTEM_TYPE,SOURCE_SYSTEM,NWCG_REPORTING_AGENCY,NWCG_REPORTING_UNIT_ID,NWCG_REPORTING_UNIT_NAME,SOURCE_REPORTING_UNIT,SOURCE_REPORTING_UNIT_NAME,...,FIRE_SIZE_CLASS,LATITUDE,LONGITUDE,OWNER_CODE,OWNER_DESCR,STATE,COUNTY,FIPS_CODE,FIPS_NAME,Shape
0,1,1,FS-1418826,FED,FS-FIRESTAT,FS,USCAPNF,Plumas National Forest,0511,Plumas National Forest,...,A,40.036944,-121.005833,5.0,USFS,CA,63,063,Plumas,b'\x00\x01\xad\x10\x00\x00\xe8d\xc2\x92_@^\xc0...
1,2,2,FS-1418827,FED,FS-FIRESTAT,FS,USCAENF,Eldorado National Forest,0503,Eldorado National Forest,...,A,38.933056,-120.404444,5.0,USFS,CA,61,061,Placer,b'\x00\x01\xad\x10\x00\x00T\xb6\xeej\xe2\x19^\...
2,3,3,FS-1418835,FED,FS-FIRESTAT,FS,USCAENF,Eldorado National Forest,0503,Eldorado National Forest,...,A,38.984167,-120.735556,13.0,STATE OR PRIVATE,CA,17,017,El Dorado,b'\x00\x01\xad\x10\x00\x00\xd0\xa5\xa0W\x13/^\...
3,4,4,FS-1418845,FED,FS-FIRESTAT,FS,USCAENF,Eldorado National Forest,0503,Eldorado National Forest,...,A,38.559167,-119.913333,5.0,USFS,CA,3,003,Alpine,b'\x00\x01\xad\x10\x00\x00\x94\xac\xa3\rt\xfa]...
4,5,5,FS-1418847,FED,FS-FIRESTAT,FS,USCAENF,Eldorado National Forest,0503,Eldorado National Forest,...,A,38.559167,-119.933056,5.0,USFS,CA,3,003,Alpine,b'\x00\x01\xad\x10\x00\x00@\xe3\xaa.\xb7\xfb]\...

In [9]:
col_list = ['FOD_ID', 'SOURCE_SYSTEM_TYPE', 'FIRE_NAME', 'COMPLEX_NAME', 'FIRE_YEAR', 'DISCOVERY_DATE', 'DISCOVERY_DOY', 'DISCOVERY_TIME', 'STAT_CAUSE_CODE', 'STAT_CAUSE_DESCR', 'CONT_DATE', 'CONT_TIME', 'FIRE_SIZE', 'FIRE_SIZE_CLASS', 'LATITUDE', 'LONGITUDE', 'OWNER_CODE', 'OWNER_DESCR', 'STATE', 'COUNTY', 'FIPS_CODE', 'FIPS_NAME']
df = data[col_list]

In [10]:
df.head(10)

,FOD_ID,SOURCE_SYSTEM_TYPE,FIRE_NAME,COMPLEX_NAME,FIRE_YEAR,DISCOVERY_DATE,DISCOVERY_DOY,DISCOVERY_TIME,STAT_CAUSE_CODE,STAT_CAUSE_DESCR,...,FIRE_SIZE,FIRE_SIZE_CLASS,LATITUDE,LONGITUDE,OWNER_CODE,OWNER_DESCR,STATE,COUNTY,FIPS_CODE,FIPS_NAME
0,1,FED,FOUNTAIN,None,2005,2453403.5,33,1300,9.0,Miscellaneous,...,0.10,A,40.036944,-121.005833,5.0,USFS,CA,63,063,Plumas
1,2,FED,PIGEON,None,2004,2453137.5,133,0845,1.0,Lightning,...,0.25,A,38.933056,-120.404444,5.0,USFS,CA,61,061,Placer
2,3,FED,SLACK,None,2004,2453156.5,152,1921,5.0,Debris Burning,...,0.10,A,38.984167,-120.735556,13.0,STATE OR PRIVATE,CA,17,017,El Dorado
3,4,FED,DEER,None,2004,2453184.5,180,1600,1.0,Lightning,...,0.10,A,38.559167,-119.913333,5.0,USFS,CA,3,003,Alpine
4,5,FED,STEVENOT,None,2004,2453184.5,180,1600,1.0,Lightning,...,0.10,A,38.559167,-119.933056,5.0,USFS,CA,3,003,Alpine
5,6,FED,HIDDEN,None,2004,2453186.5,182,1800,1.0,Lightning,...,0.10,A,38.635278,-120.103611,5.0,USFS,CA,5,005,Amador
6,7,FED,FORK,None,2004,2453187.5,183,1800,1.0,Lightning,...,0.10,A,38.688333,-120.153333,5.0,USFS,CA,17,017,El Dorado
7,8,FED,SLATE,None,2005,2453437.5,67,1300,5.0,Debris Burning,...,0.80,B,40.968056,-122.433889,13.0,STATE OR PRIVATE,CA,None,None,None
8,9,FED,SHASTA,None,2005,2453444.5,74,1200,5.0,Debris Burning,...,1.00,B,41.233611,-122.283333,13.0,STATE OR PRIVATE,CA,None,None,None
9,10,FED,TANGLEFOOT,None,2004,2453187.5,183,1800,1.0,Lightning,...,0.10,A,38.548333,-120.149167,5.0,USFS,CA,5,005,Amador

In [7]:
df.isnull().sum(axis=0)

FOD_ID                      0
SOURCE_SYSTEM_TYPE          0
FIRE_NAME              957189
COMPLEX_NAME          1875282
FIRE_YEAR                   0
DISCOVERY_DATE              0
DISCOVERY_DOY               0
DISCOVERY_TIME         882638
STAT_CAUSE_CODE             0
STAT_CAUSE_DESCR            0
CONT_DATE              891531
CONT_TIME              972173
FIRE_SIZE                   0
FIRE_SIZE_CLASS             0
LATITUDE                    0
LONGITUDE                   0
OWNER_CODE                  0
OWNER_DESCR                 0
STATE                       0
COUNTY                 678148
FIPS_CODE              678148
FIPS_NAME              678148
dtype: int64

In [8]:
df.dtypes

FOD_ID                  int64
SOURCE_SYSTEM_TYPE     object
FIRE_NAME              object
COMPLEX_NAME           object
FIRE_YEAR               int64
DISCOVERY_DATE        float64
DISCOVERY_DOY           int64
DISCOVERY_TIME         object
STAT_CAUSE_CODE       float64
STAT_CAUSE_DESCR       object
CONT_DATE             float64
CONT_TIME              object
FIRE_SIZE             float64
FIRE_SIZE_CLASS        object
LATITUDE              float64
LONGITUDE             float64
OWNER_CODE            float64
OWNER_DESCR            object
STATE                  object
COUNTY                 object
FIPS_CODE              object
FIPS_NAME              object
dtype: object

In [11]:
df = df.dropna(subset=['CONT_DATE'])

In [12]:
len(df)

988934

In [21]:
df.isnull().sum(axis=0)

FOD_ID                      0
SOURCE_SYSTEM_TYPE          0
FIRE_NAME              957189
COMPLEX_NAME          1875282
FIRE_YEAR                   0
DISCOVERY_DATE              0
DISCOVERY_DOY               0
DISCOVERY_TIME         882638
STAT_CAUSE_CODE             0
STAT_CAUSE_DESCR            0
CONT_DATE              891531
CONT_TIME              972173
FIRE_SIZE                   0
FIRE_SIZE_CLASS             0
LATITUDE                    0
LONGITUDE                   0
OWNER_CODE                  0
OWNER_DESCR                 0
STATE                       0
COUNTY                 678148
FIPS_CODE              678148
FIPS_NAME              678148
DURATION               891531
dtype: int64

In [16]:
df.head()

,FOD_ID,SOURCE_SYSTEM_TYPE,FIRE_NAME,COMPLEX_NAME,FIRE_YEAR,DISCOVERY_DATE,DISCOVERY_DOY,DISCOVERY_TIME,STAT_CAUSE_CODE,STAT_CAUSE_DESCR,...,FIRE_SIZE_CLASS,LATITUDE,LONGITUDE,OWNER_CODE,OWNER_DESCR,STATE,COUNTY,FIPS_CODE,FIPS_NAME,DURATION
0,1,FED,FOUNTAIN,None,2005,2453403.5,33,1300,9.0,Miscellaneous,...,A,40.036944,-121.005833,5.0,USFS,CA,63,063,Plumas,0.0
1,2,FED,PIGEON,None,2004,2453137.5,133,0845,1.0,Lightning,...,A,38.933056,-120.404444,5.0,USFS,CA,61,061,Placer,0.0
2,3,FED,SLACK,None,2004,2453156.5,152,1921,5.0,Debris Burning,...,A,38.984167,-120.735556,13.0,STATE OR PRIVATE,CA,17,017,El Dorado,0.0
3,4,FED,DEER,None,2004,2453184.5,180,1600,1.0,Lightning,...,A,38.559167,-119.913333,5.0,USFS,CA,3,003,Alpine,5.0
4,5,FED,STEVENOT,None,2004,2453184.5,180,1600,1.0,Lightning,...,A,38.559167,-119.933056,5.0,USFS,CA,3,003,Alpine,5.0

In [14]:
df.loc[:,'DURATION'] = df['CONT_DATE'] - df['DISCOVERY_DATE']

C:\Users\betsy_k\Anaconda3\lib\site-packages\pandas\core\indexing.py:844: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
C:\Users\betsy_k\Anaconda3\lib\site-packages\pandas\core\indexing.py:965: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

In [16]:
df["DURATION"].describe().astype(np.int64)

count    988934
mean          1
std          15
min           0
25%           0
50%           0
75%           0
max        4018
Name: DURATION, dtype: int64

In [29]:
import datetime as dt

In [30]:
df['DATE'] = pd.to_datetime(df['DISCOVERY_DATE'] - pd.Timestamp(0).to_julian_date(), unit='D')
df.head()

C:\Users\betsy_k\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,FOD_ID,SOURCE_SYSTEM_TYPE,FIRE_NAME,COMPLEX_NAME,FIRE_YEAR,DISCOVERY_DATE,DISCOVERY_DOY,DISCOVERY_TIME,STAT_CAUSE_CODE,STAT_CAUSE_DESCR,...,LATITUDE,LONGITUDE,OWNER_CODE,OWNER_DESCR,STATE,COUNTY,FIPS_CODE,FIPS_NAME,DURATION,DATE
0,1,FED,FOUNTAIN,None,2005,2453403.5,33,1300,9.0,Miscellaneous,...,40.036944,-121.005833,5.0,USFS,CA,63,063,Plumas,0.0,2005-02-02
1,2,FED,PIGEON,None,2004,2453137.5,133,0845,1.0,Lightning,...,38.933056,-120.404444,5.0,USFS,CA,61,061,Placer,0.0,2004-05-12
2,3,FED,SLACK,None,2004,2453156.5,152,1921,5.0,Debris Burning,...,38.984167,-120.735556,13.0,STATE OR PRIVATE,CA,17,017,El Dorado,0.0,2004-05-31
3,4,FED,DEER,None,2004,2453184.5,180,1600,1.0,Lightning,...,38.559167,-119.913333,5.0,USFS,CA,3,003,Alpine,5.0,2004-06-28
4,5,FED,STEVENOT,None,2004,2453184.5,180,1600,1.0,Lightning,...,38.559167,-119.933056,5.0,USFS,CA,3,003,Alpine,5.0,2004-06-28

In [33]:
df['MONTH'] = pd.DatetimeIndex(df['DATE']).month
df['DAY_OF_WEEK'] = df['DATE'].dt.weekday
df.head()

C:\Users\betsy_k\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\betsy_k\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,FOD_ID,SOURCE_SYSTEM_TYPE,FIRE_NAME,COMPLEX_NAME,FIRE_YEAR,DISCOVERY_DATE,DISCOVERY_DOY,DISCOVERY_TIME,STAT_CAUSE_CODE,STAT_CAUSE_DESCR,...,OWNER_CODE,OWNER_DESCR,STATE,COUNTY,FIPS_CODE,FIPS_NAME,DURATION,DATE,MONTH,DAY_OF_WEEK
0,1,FED,FOUNTAIN,None,2005,2453403.5,33,1300,9.0,Miscellaneous,...,5.0,USFS,CA,63,063,Plumas,0.0,2005-02-02,2,2
1,2,FED,PIGEON,None,2004,2453137.5,133,0845,1.0,Lightning,...,5.0,USFS,CA,61,061,Placer,0.0,2004-05-12,5,2
2,3,FED,SLACK,None,2004,2453156.5,152,1921,5.0,Debris Burning,...,13.0,STATE OR PRIVATE,CA,17,017,El Dorado,0.0,2004-05-31,5,0
3,4,FED,DEER,None,2004,2453184.5,180,1600,1.0,Lightning,...,5.0,USFS,CA,3,003,Alpine,5.0,2004-06-28,6,0
4,5,FED,STEVENOT,None,2004,2453184.5,180,1600,1.0,Lightning,...,5.0,USFS,CA,3,003,Alpine,5.0,2004-06-28,6,0

In [34]:
#export final file
output_data_file = "Resources/wildfires.csv"

In [35]:
df.to_csv(output_data_file, index=False, header=True)